name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Instalação e Testes
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    # Build da aplicação
    - name: Build Docker image
      run: |
        docker build -t myapp:latest .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Acesso à instância EC2 via SSH
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.AWS_EC2_IP }}
        username: ubuntu
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          # Atualizar o código e reiniciar os containers
          cd /path/to/app
          git pull origin main
          docker-compose down
          docker-compose up -d
